
-- 테이블 생성
CREATE TABLE MEMBER( -- TABLE 이름이 MEMBER
    ID VARCHAR2(30)
    , PWD VARCHAR2(100)
    , NICK VARCHAR2(10)
    , GENDER CHAR(1)
    , ENROLL_DATE TIMESTAMP
);

-- MEMBER 테이블의 모든 데이터 조회
SELECT *
FROM MEMBER;

-- MEMBER 테이블에 INSERT
INSERT INTO MEMBER(ID, PWD, NICK, GENDER, ENROLL_DATE) VALUES('AYJ', '1234','DUSWN','F',SYSDATE);

INSERT INTO MEMBER(ID, PWD, NICK, GENDER, ENROLL_DATE) VALUES('USER01', '1234','NICK01','F',SYSDATE);

-- GENDER을 NULL값으로 입력
INSERT INTO MEMBER(ID, PWD, NICK, GENDER, ENROLL_DATE) VALUES('USER02', '1234','NICK02', NULL, SYSDATE); 

-- GENDER 빼고 INSERT 해보기
INSERT INTO MEMBER(ID, PWD, NICK, ENROLL_DATE) VALUES('USER03', '1234','NICK03', SYSDATE);

--(ID, PWD, NICK, GENDER, ENROLL_DATE) : 어차피 모든 칼럼 다 넣으므로 칼럼명 안 써도 됨.
INSERT INTO MEMBER VALUES('NICK99', '1234','USER99','F',SYSDATE);

--MEMBER 테이블 UPDATE
UPDATE MEMBER SET 
    PWD = '7777'-- 원하는 칼럼에 원하는 값 넣을 수 있음
    , ENROLL_DATE = SYSDATE
    WHERE  ID = 'AYJ';-- 특정 값이 들어있는행에 대해서만 바뀜

--MEMBER TABLE DELETE
DELETE MEMBER
WHERE ID = 'NICK99'
;

COMMIT; -- SAVE POINT 만들기
ROLLBACK; -- 해당 포인트로 돌아가는 것

INSERT INTO MEMBER VALUES('NICK99', '1234','USER99','F',SYSDATE);

SELECT *
FROM MEMBER;

ROLLBACK;



















