DROP TABLE USER_TBL;

CREATE TABLE USER_TBL( 
    USER_ID VARCHAR2(20) PRIMARY KEY
    , USER_PW VARCHAR2(20) NOT NULL
    , USER_NAME VARCHAR2(20) NOT NULL
    , ENROLLDATE DATE
);

SELECT *
FROM USER_TBL;

COMMENT ON COLUMN USER_TBL.USER_ID IS '아이디';
COMMENT ON COLUMN USER_TBL.USER_PW IS '패스워드';
COMMENT ON COLUMN USER_TBL.USER_NAME IS '이름';
COMMENT ON COLUMN USER_TBL.ENROLLDATE IS '가입일';
